CC = gcc
LIB = -lpthread
EXE0 = mutex_lock
EXE1 = read_write_lock

$(EXE0): $(EXE0).exe
        ./$<      

%.exe : %.c
        $(CC) $(LIB) -o $@ $^
        
$(EXE1): $(EXE1).exe
        ./$<      

%.exe : %.c
        $(CC) $(LIB) -o $@ $^

all: $(EXE0) $(EXE1)

clean:
        rm -f *.exe
